CREATE TABLE IF NOT EXISTS ROLES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL UNIQUE
);

INSERT IGNORE INTO ROLES (NAME) VALUES
('ADMIN'),
('CUSTOMER'),
('SUPPORT');